import sys
import os
import webbrowser

#!/usr/bin/env python3
"""
Gamma.py - generate a basic HTML file

Usage:
    python Gamma.py [output.html]
"""

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; max-width:900px; margin:2rem auto; padding:0 1rem; color:#222; }}
  header {{ border-bottom:1px solid #e6e6e6; padding-bottom:1rem; margin-bottom:1rem; }}
  footer {{ border-top:1px solid #e6e6e6; margin-top:2rem; padding-top:1rem; color:#666; font-size:.9rem; }}
  a {{ color:#0366d6; text-decoration:none; }}
  a:hover {{ text-decoration:underline; }}
</style>
</head>
<body>
<header>
  <h1>{heading}</h1>
  <p>{subtitle}</p>
</header>
<main>
{content}
</main>
<footer>
  <p>Generated by Gamma.py</p>
</footer>
</body>
</html>
"""

DEFAULT_CONTENT = """<p>This is a basic HTML template created by a Python script.</p>
<ul>
  <li>Simple structure: head, body, header, main, footer</li>
  <li>Responsive viewport meta</li>
  <li>Minimal CSS for readability</li>
</ul>
<p>Learn more at <a href="https://example.com" target="_blank" rel="noopener">Example</a>.</p>
"""

def generate_html(title="Basic HTML Page",
                  heading="Hello, world!",
                  subtitle="A simple HTML template",
                  content=DEFAULT_CONTENT,
                  filename="index.html"):
    html = HTML_TEMPLATE.format(title=title, heading=heading, subtitle=subtitle, content=content)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    path = os.path.abspath(filename)
    print(f"Wrote {path}")
    try:
        webbrowser.open_new_tab("file://" + path)
    except Exception:
        pass

if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "index.html"
    generate_html(filename=out) 